### ISSUE TITLE
[feature]: consider adding tooltips on hover

### ISSUE THREAD

**Issue by AdrianSkar** [AdrianSkar/42Madrid-stylus#1]
Maybe some descriptive small tooltip to show the actual/current issue.

```css
/* Common tooltip styles */
#cluster-24 g text[title],
#cluster-25 g text[title],
#cluster-26 g text[title] {
  position: relative;
}

#cluster-24 g text[title]::before,
#cluster-25 g text[title]::before,
#cluster-26 g text[title]::before {
  content: attr(title);
  position: absolute;
  bottom: 100%;
  left: 50%;
  transform: translateX(-50%);
  padding: 5px;
  background: rgba(0,0,0,0.8);
  color: white;
  border-radius: 4px;
  font-size: 12px;
  white-space: nowrap;
  visibility: hidden;
  opacity: 0;
  transition: opacity 0.2s;
}

#cluster-24 g text[title]:hover::before,
#cluster-25 g text[title]:hover::before,
#cluster-26 g text[title]:hover::before {
  visibility: visible;
  opacity: 1;
}

/* Not available seats */
#cluster-24 g.r1.middle text:nth-child(1) { title: "Bocal"; }
#cluster-24 g.r2.middle text:nth-child(2) { title: "Needs reinstall"; }

/* Issue seats */
#cluster-24 g.r1.middle text:nth-child(6) { title: "Bad BT"; }
#cluster-24 g.r17.middle text:nth-child(4) { title: "Bad BT"; }
/* Add more title attributes for other seats... */
```
